#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setting JAVA_HOME
#export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre

# Path to Android SDK
export ANDROID_HOME=/Users/16535/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Path to my scripts
export PATH=$PATH:/Users/16535/myscripts

# added by Anaconda2 4.0.0 installer
#export PATH="/opt/myapps/anaconda2/bin:$PATH"

# My aliases
alias tomcat='cd /Users/16535/Documents/WMS/services/wms/apache-tomcat-7.0.42'
alias wms='cd /Users/16535/Documents/WMS'
alias vi=vim
alias e5='ssh arunkumar.g@e5'
alias tomcat='/Users/16535/Documents/WMS/services/wms/apache-tomcat-7.0.42'
alias cppropini='cp /Users/16535/Documents/WMS/repos/wmsweb/myntra-wms-web/app/utils/properties.ini.txt /Users/16535/Documents/WMS/repos/wmsweb/myntra-wms-web/app/utils/properties.ini'
#alias pyact='source activate'
#
#
#alias pydeact='source deactivate'

#alias ipy='ipython'
#alias py='python'

#alias cdwww='cd /var/www/html'
#alias cdjunk='cd ~/Documents/Junk'
#alias cdprojs='cd ~/Documents/Projects'
#alias cddocs='cd ~/Documents'
#alias cddownlds='cd ~/Downloads'
#alias cdandroid='cd $ANDROID_HOME/'
#alias cdkaggle='cd /home/arun/Documents/Projects/Kaggle'

#alias agu='sudo apt-get update'
#alias pipi='sudo pip install -H'

# youtube-dl alias
#alias ytubef="youtube-dl -o '%(title)s.%(ext)s' --restrict-filenames"
#alias ytubep="youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"

# just source that file to enable shell completion on umake
#eval "$(register-python-argcomplete bin/umake)"

# NVM
#export NVM_DIR="/home/arun/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# NVM Remote Fix
#export NVM_NODEJS_ORG_MIRROR="http://nodejs.org/dist"
#export NVM_IOJS_ORG_MIRROR="http://npm.taobao.org/mirrors/iojs/"

# Add nvm to PATH
source /usr/local/opt/nvm/nvm.sh

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

# Jenv
#export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"

# added by Anaconda2 4.1.1 installer
export PATH="/Users/16535/anaconda/bin:$PATH"

# Apache Spark
export PATH="/Users/16535/spark-1.6.2-bin-hadoop2.6/bin:$PATH"

# Go PATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
